-- phpMyAdmin SQL Dump
-- version 3.5.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 29, 2012 at 02:47 AM
-- Server version: 5.5.24-log
-- PHP Version: 5.4.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `db_equipment`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_products`
--

CREATE TABLE IF NOT EXISTS `tbl_products` (
  `product_id` smallint(4) unsigned NOT NULL AUTO_INCREMENT,
  `product_brand` varchar(200) NOT NULL,
  `product_model` varchar(500) NOT NULL,
  `product_price` varchar(25) NOT NULL,
  `product_description` varchar(5000) NOT NULL,
  `product_feat1` varchar(500) NOT NULL,
  `product_feat2` varchar(500) NOT NULL,
  `product_feat3` varchar(500) NOT NULL,
  `product_feat4` varchar(500) NOT NULL,
  `product_type` varchar(250) NOT NULL,
  `product_image` varchar(150) NOT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=36 ;

--
-- Dumping data for table `tbl_products`
--

INSERT INTO `tbl_products` (`product_id`, `product_brand`, `product_model`, `product_price`, `product_description`, `product_feat1`, `product_feat2`, `product_feat3`, `product_feat4`, `product_type`, `product_image`) VALUES
(1, 'Audio-Technica', 'AT-LP120-USB Turntable w/ Built-In Pre-Amp', '299.95', 'Updated USB version of Audio-Technica''s direct-drive turntable. With Technics prices at an all-time high, the Audio-Technica AT-LP120 USBs offers a secondary, more inexpensive option with features the 1200 does not have. Firstly, you will notice that the AT-LP120s looks very similar to the 1200. Audio-Technica has basically borrowed the 1200''s popular layout and design. The major difference is that the AT-PL120s'' body is mostly constructed of plastic (vs. the metal of the 1200); however the key parts remain metal (platter and tonearm). ', 'USB connectivity', 'direct drive motor', 'built-in preamp', 'pitch control', 'turntable', 'turntables/at-lp120-usb.jpg'),
(2, 'Audio-Technica', 'AT-LP1240-USB DJ Turntable', '449.00', 'The key to AT-LP1240-USB''s design is that it borrows its key functionality and design from the Technics 1200. The cast metal platter and rubberized base give the turntable that essential heaviness feel. Even the black gloss finish seems more solid than the standard plastic top turntable faceplate. The high-torque motor rivals the force of the 1200, and the adjustable tonearm features similar controls (tracking weight, anti-skate, height adjustment) to the 1200. The quartz lock button is a popular feature borrowed from the 1200 MK5 model. In addition, the AT-LP1240-USB includes many deluxe features that you will not find on the Technics 1200. The USB output and built-in pre-amplifier are excellent features for those who are ripping vinyl. The removable cords and under-platter closed design address some of the 1200''s biggest flaws. The reverse play, dual start / stop buttons, and start / stop controls will appeal to DJs that need more control.', 'reverse play button', 'S-shaped tonearm with adjustable tracking force, height adjustment, and anti-skate adjustment', 'powerful, high torque direct drive motor', 'hydraulic arm-lift mechanism', 'turntable', 'turntables/at-lp1240-usb.jpg'),
(3, 'Audio-Technica', 'AT-LP60 Automatic Turntable + Pre-Amp', '99.00', 'Audio-Technica''s AT-LP60 is an simple, affordable, fully automatic belt-drive turntable. The turntable features a built-in switchable phono preamp making it perfect for listening to your 33 1/3 or 45 RPM records on your home stereo, computer or any other component that has no dedicated turntable input. Includes an integral Audio-Technica Dual Magnet phono cartridge with replaceable stylus, dust cover, 45 adapter, and all necessary cables. Recommended for anyone looking for a basic, no-frills turntable to listen to their vinyl on.', 'fully automatic operation with two speeds: 33-1/3 and 45 RPM', 'professional aluminum platter', 'included cables connect to your stereo or powered speakers', 'switchable built-in pre-amplifier with line-level RCA output cables', 'turntable', 'turntables/at-lp60.jpg'),
(4, 'Numark', 'DJ In A Box Turntables + Mixer Package', '299.99', 'Numark''s DJ In A Box is a complete DJ package with belt-drive turntables and an iPod ready mixer for performing with vinyl, iPod or iPhone, and more. It comes with the iM1, the world''s first DJ mixer that records your mix to your iPod. You can also perform with tracks from your iPod, connect optional gear like CD players, mics, and preview your mix with the included HF125 DJ headphones.', 'TT1610 belt-drive turntables', 'iM1 two-channel mixer with dock for iPod', 'rugged, reliable faders', 'HF125 DJ headphones', 'turntable', 'turntables/numark-dj-in-a-box.jpg'),
(5, 'Numark', 'iBattle Pack Turntables + Mixer Package', '399.00', 'Numark''s iBATTLEPACK is a complete DJ package with direct-drive turntables and an iPod ready mixer for performing with vinyl, iPod or iPhone, and more. iBATTLEPACK features iM1, the world''s first DJ mixer that records your mix to your iPod. You can also perform with tracks from your iPod, connect optional gear like CD players, mics, and preview your mix with the included HF125 DJ headphones.', 'TT1625 direct-drive turntables', 'iM1 two-channel mixer with dock for iPod', 'rugged, reliable faders', 'HF125 DJ headphones', 'turntable', 'turntables/numark-ibattle.jpg'),
(6, 'Shure', 'SC35C Cartridge', '39.95', 'The SC35C is Shure''s classic workhorse, a highly durable cartridge with skip-resistance comparable to the M44G. Before the 44 series came out, everyone was using these and many hip hop djs still swear by them. The sound quality is about the same as the 447 (heavy on bass response), with an output of 5.0mV. They are a bit more rugged than the M44 series, but they also put more wear on your records. An excellent beginner to intermediate choice. ', 'all purpose dj cartridge', 'good skip resistance', 'standard 1/2\\" mount', '1 year warranty', 'catridge', 'catridges/shure-sc35c.jpg'),
(7, 'Stanton', '400.V3 Cartridge', '39.00', 'Stanton''s entry level cartridge which boasts an extremely high output for something in this price range: 10mV, which is about the same as a high end Ortofon. Pretty impressive. It also comes with Stanton''s mark of durability (they really do make the most rugged cartridges on the market), which makes this an easy choice for beginners. It comes with a spherical stylus, so scratching is not a problem although the high tracking force will wear your records a bit. You can''t beat this for the money though.', 'high 10mV output for loud sound', 'spherical stylus', '2-coil pickup increases stereo imaging while providing high output', 'rugged and durable construction', 'catridge', 'catridges/stanton-400.jpg'),
(8, 'Stanton', '500.V3 Cartridge', '49.00', 'Stanton has redesigned their entire line of cartridges, giving them a new look and improving performance with greater tracking ability and less record wear across the entire line. The 500 cartridge remains one of the best cartridge values with an extremely reliable track record. This has been an industry standard for broadcast and club djs for many many years, with a solid construction that can withstand tons of abuse. It has a fairly loud and clear output, and comes recommended for beginners or your back up set.', 'multi-function club dj cartridge', 'concorde-style cartridge', 'detailed sound reproduction', 'good skip resistance, low tracking force', 'catridge', 'catridges/stanton-500.jpg'),
(9, 'Stanton', '680.V3 Cartridge', '79.99', 'Stanton''s 680 cartridge has been a favorite amongst club deejays and those demanding full, loud sound for many years. This newest version has balanced that famous club sound quality with more modern dj performance so that it not only sounds great, but can also do everything you need (scratch, back cue, etc). Part of the reason for this is the spherical stylus (better for scratching) that the 680 now uses, but it''s also due to the 680''s extremely forgiving suspension. It was designed for abusive use in club situations- which means wobbly tables, uneven turntables, bumping, etc- and this translates just as well to scratching. The sound specs have not changed at all, and it still offers a wide frequency response at 20Hz to 18kHz and big 7.0mV output. Recommended for club use for their sound quality, reliability, and ruggedness.', 'all-around DJ cartridge, good for the club', 'spherical stylus', 'wide frequency response', '7.0mV output', 'catridge', 'catridges/stanton-680.jpg'),
(10, 'Technics', 'SL-1200MK2 Turntable - Silver', '1,155.00', 'This is the turntable that first established the type of high torque (motor strength), accurate pitch (speed control), quality tone arm (aids in skip resistance), and superior sound that is required by djs; and after 25+ years it is still the standard by which all other turntables are judged. Every other turntable that has come since has patterned their design off this legendary piece of equipment, and the reason is simple: the 1200MK2 is about as close to perfection as you can get with a piece of machinery. It functions beautifully and the durability and construction are unmatched. The body and major components are made of steel.', 'industry standard direct drive turntable', 'powerful, high torque motor', 'heavyweight construction', 'built to last', 'turntable', 'turntables/technics-sl-1200-silver.jpg'),
(12, 'Technics', 'SL-1210M5G Turntable', '1,500.00', 'The 1210 M5G is subtitled the \\"grand master\\" and takes over the top of the line position for Technics'' line of turntables. The major improvement here, and the feature which is exclusive to the 1210M5G, is the pitch control. It is now completely digital, which means you should never have the problem of mismatched pitch ranges, and it also gives you the ability to choose between two separate pitch ranges: the standard +/-8 range and the larger +/-16 range. The color scheme, style and finish are also exclusive to the M5G and includes a blue stylus pop-up light, blue lights for both pitch ranges, a unique metallic black finish, and brushed steel hardware for everything down to the 45 adaptor. ', 'includes a switch to change voltage between 110/120 and 220', 'features European prong plug with US adaptor', '+/-8 and +/-16 pitch control', 'pitch control reset button', 'turntable', 'turntables/technics-sl-1210.jpg'),
(13, 'Ecler', 'NUO 2.0 Mixer', '449.00', 'The NUO2.0 is the upgraded version of Ecler''s popular NUO2 2-channel mixer. The NUO2.0 boasts improved electronics for even better sound quality, an anodized-aluminum faceplate with etched lettering and graphics, and high quality VU meters borrowed from the EVO5. This versatile mixer also features high quality EQ''s, kill switches, and FX sends, as well as upgradable faders with curve control and reverse to suit the needs of both mix and scratch DJs.', 'Crossfader upgradeable to ETERNAL magnetic x-fader (same as HAK series)', '2 mixing channels', '1 Microphone/Line channel', '2 Phono and 3 Line inputs', 'mixer', 'mixers/ecler-nuo2.jpg'),
(14, 'Ecler', 'NUO 3.0 Mixer', '649.00', 'Upgraded version of Ecler''s NUO 3-channel mixer. The Nuo3.0 boasts upgraded electronics and analog components for even better sound quality (Ecler mixers are reknowned to have some of the best sound in the industry). This robust and versatile mixer features full cut, precise EQs with large ergonomic knobs, pro FX send and loop functions, as well as upgradeable faders with curve and cut-in to suit all styles of DJing. ', '3 mixing channels', '3 Phono and 3 Line inputs', '1 balanced XLR Microphone input', 'Master output balanced XLR and unbalanced RCA', 'mixer', 'mixers/ecler-nuo3.jpg'),
(15, 'Ecler', 'NUO 4.0 Mixer', '799.00', 'Updated version of Ecler''s NUO4 4-channel mixer. Unlike the previous version, the Nuo4.0 does NOT feature MIDI control capabilities. It does however feature upgraded electronics and analog components in order to provide the highest performance and sound capabilities. The Nuo4.0 features professional EQ, FX, and crossfader functions making it a perfect mixer for all styles - in the home studio or club installation.', '4 mixing channels', '4 Phono and 4 Line inputs', '2 balanced XLR Microphone inputs', 'Master output XLR and RCA', 'mixer', 'mixers/ecler-nuo4.jpg'),
(16, 'Pioneer', 'DJM-250 Mixer - White', '349.00', 'With the DJM-250, you can combine EQ effects with 2 filters to perform mixes that sound like they were meant to be. Add that to the DJM-250''s pro features and you''ve got a mixer like no other on the market. It''s loaded with 8 inputs to connect with an array of sources, including 1 MIC input for MCing at parties. The mixer mirrors the layout of its bigger brothers to deliver the professional experience. Plus the XLR balanced output guarantees the high quality sound expected from our club standard mixers, making it perfect for DJing at home, parties or in music bars. ', '2 channel mixer w/ 48 kHz/24-bit full digital processing', '3-band isolator type EQ', 'sound color fitler', 'fader start function', 'mixer', 'mixers/pioneer-djm250.jpg'),
(17, 'Pioneer', 'DJM-250-K Mixer - Black', '349.00', 'With the DJM-250, you can combine EQ effects with 2 filters to perform mixes that sound like they were meant to be. Add that to the DJM-250''s pro features and you''ve got a mixer like no other on the market. It''s loaded with 8 inputs to connect with an array of sources, including 1 MIC input for MCing at parties. The mixer mirrors the layout of its bigger brothers to deliver the professional experience. Plus the XLR balanced output guarantees the high quality sound expected from our club standard mixers, making it perfect for DJing at home, parties or in music bars.', '2 channel mixer w/ 48 kHz/24-bit full digital processing', '3-band isolator type EQ', 'sound color fitler', 'fader start function', 'mixer', 'mixers/pioneer-djm250-k.jpg'),
(18, 'Pioneer', 'DJM-700-K Mixer', '999.00', 'The DJM-700 is the latest high-end 4-channel mixer from Pioneer, with similar features as its big brother the DJM-800, plus several new ones to set it apart from the rest. Featuring superior sound quality and functionality and cutting edge effects(including the world''s first Effect Frequency Filter) and MIDI connectivity the DJM-700 is definitely designed to set new standards for working DJs in the club, bar or studio.', '4 channels with MIDI + on board effects', '96kHz/24-bit digital sampling system with 32-bit DSP', 'fader curve for both crossfader and channel faders', 'digital read out for effects settings + BPM counter', 'mixer', 'mixers/pioneer-djm-700.jpg'),
(19, 'Rane', 'Empath Mixer - Black', '999.00', 'Packaged in a sleek black casing, the Empath mixer combines the vision of Grandmaster Flash and Rane technology. Compact size, exceptional performance and advanced features set the Empath mixer apart. The Empath is the most able 3-channel, 10\\" format mixer available. The name implies: understanding, awareness and sensitivity to the needs of DJs. ', 'two kinds of fader caps', 'multiple outputs', 'Accelerated-Slope, full-cut, 3-band tone controls', 'crossfader assign switches allow any Input Channel', 'mixer', 'mixers/rane-empath.jpg'),
(20, 'Rane', 'Empath Rotary Mixer', '1,049.00', 'The Empath mixer combines the vision of Grandmaster Flash and Rane technology. Compact size, exceptional performance and advanced features set the Empath mixer apart. The Empath is the most able 3-channel, 10\\" format mixer available. The name implies: understanding, awareness and sensitivity to the needs of DJs.', 'Low and High headphone tone controls make your headphones sound better', 'both 1/4\\" and 3.5 mm headphone jacks are simultaneously usable', 'two assignable CD triggers work with any CD player with fader start ability', 'Level meters view Stereo Cue, Stereo Master Mix, Split Cue or Main Output signals', 'mixer', 'mixers/rane-rotary.jpg'),
(21, 'Rane', 'Sixty-Eight Serato Mixer', '2,599.00', 'Rane''s Sixty Eight is the first professional DJ mixer with two USB 2.0 High Speed ports with support for real-time connection of two computers meaning two DJs can use Scratch Live in parallel and/or seamlessly transition from one DJ to another. The mixer is loaded with other advanced features including easy to use internal digital effects, control of up to four decks with a single laptop, direct control of over 30 Scratch Live library, cue and loop functions, and studio-grade phono preamps, USB and S/PDIF inputs for the ultimate blend of analog and digital sources. ', '2 independent USB 2.0 High Speed ports', 'support for 2, 3 or 4 Virtual Decks on one or two computers', 'direct control of over 30 Scratch Live Library, Cue and Loop functions', 'four full-featured input channels', 'mixer', 'mixers/rane-68.jpg'),
(22, 'AIAIAI', 'AIAIAI x Teenage Engineering PX-0 Earphones', '64.00', 'Jesper Kouthoofd from Teenage Engineering has designed the PX-0 and the aesthetics of the earphone follows the same design-ethos as the OP-1 synthesizer. The sound has been tunes by AIAIAI and the result is a well-defined frequency response and full spectrum sound with an emphasis on low and mid range, but still with distinct clarity in the high-range frequencies. The PX-0 comes with three different sleeves for better custom fit. The PX-0 is compatible with iPhone, iPad, and iPod. ', 'same design-ethos as the Teenage Engineering''s OP-1 synth', 'on-cable mic works with most portable devices', 'full frequency response with emphasis on low and mid range', 'includes 3 sleeves for comfortable fit', 'headphones', 'headphones/aiaiai-teenage.jpg'),
(23, 'AIAIAI', 'Pipe Headset w/ Mic - Fool''s Gold Edition', '80.00', 'The Pipe Earphone offers impressive sound quality and overall strength in an organic and ergonomic design. Made from lightweight and highly resilient materials this earphone displays an elegant coherency between the overall design and the individual parts. The 9mm precision-engineered driver provides a highly detailed full-spectrum sound experience from the softest bass to the crispiest high notes. ', '3 Button in-line Microphone with call/music/volume control', 'sound quality is fine tuned by C4 Studios', 'earphone sleeves deliver external noise reduction', 'includes three sets of earphone sleeves for an accurate fit', 'headphones', 'headphones/aiaiai-pipes.jpg'),
(24, 'AIAIAI', 'TMA-1 DJ Headphones', '199.00', 'The one-piece TMA-1 headband consists of a strong, durable and flexible nylon material, which provides full flexibility when wearing and positioning the headphones during DJing. The two different cushions can be changed easily with the click release function, so the headphones fit all situations- from a noisy club environment to just being on the road. The speaker is protected by the cushion plate with integrated filter and provides the richest sound that is available today along with the most durable driver technology.', 'rich quality sound from high quality audio components', 'internal speakers are fully protected', 'strong, flexible headband', 'headphone cord coil for extra give', 'headphones', 'headphones/aiaiai-tma.jpg'),
(25, 'Grado', 'GR8 In-Ear Headphones', '299.00', 'Grado enters the in-ear market with the GR8. The GR8''s feature Grado''s renowned quality and top notch sound reproduction as well as a proprietary wide bandwidth moving armature design providing the listener with unsurpassed performance. The small size allows earphone to nestle well within the ear canal, maintaining an excellent air seal for improved bass and reduction of outside noise without causing discomfort. Includes 3 pair ear tips (small, medium, large; proprietary blend of two silicon rubber materials) for a custom fit, 4 ear wax proof cloths, and 2 ear wax proof cloth rings.', 'on-ear style headphone with over-the-ear functionality', 'custom designed single touch controller for seamless play/pause and answer/end technology', 'plush ear cup cushioning and soft, pliable headband for hours of comfort', 'premium woven cloth cording to prevent tangling', 'headphones', 'headphones/grado-gr8.jpg'),
(26, 'Grado', 'GS1000i Headphones', '995.00', 'What does the i stand for in the new GS1000i from Grado? Improved, that''s what! Featuring a new species of handcrafted Mahogany earpieces made using an intricate curing process; Grado has been able to optimize the tonal quality. The GS1000i uses new upgraded dynamic transducers and the new 8 conductor cable design. All this, new wood, driver and cable designs result in improved control and stability of the upper and lower range of the frequency spectrum with both better supporting the GS1000i''s new world renowned midrange. Grado''s GS1000i cushion design actually creates a \\"room\\" for the ears to sit, creating a larger soundstage and greater spatial experience for the listener.', 'legendary headphones from Brooklyn company', 'Hi-Fi Choice''s best headphone over 200', 'ridiculous frequency response', 'handcrafted Mahogany earpieces made using an intricate curing process for optimal tonal quality', 'headphones', 'headphones/grado-gs1000.jpg'),
(27, 'Grado', 'PS1000 Headphones', '1,695.00', 'From Grado - \\"The PS1000''s are the very best Grado headphone ever made.\\" That is quite a statement, especially from Grado, a company renowned for their top notch headphones. Obviously the PS1000''s are for serious audiophiles that demand the best in every aspect of sonic detailing. The thing that makes these headphones so special is the hybrid metal/wooden construction that incorporates the tone and timbre of the RS1''s, while maintaining the superior Grado mid-range and a resonance reduced decay. The PS1000''s also feature large cushions as providing a very comfortable fit on the head, great for very long listening sessions, and also create large sound and headstage.', 'legendary headphones from Brooklyn company', 'Grado''s self-proclaimed \\"finest headphone ever\\", multiple award winner', 'ridiculous frequency response', 'designed for maximum comfort', 'headphones', 'headphones/grado-ps1000.jpg'),
(28, 'Urbanears', 'Plattan Headphones - Indigo Denim Edition', '80.00', 'The Indigo Denim Plattan is the second in Urbanears'' \\"editions\\" line of headphones. The editions headphones offer something special, and with the denim model, they feature unique all-over denim fabric on the the padded headband and ear cushions. These headphones inherit the features of other Plattanss including the classic style that can be folded as small as your fist for ultimate portability, the handmade 36mm drivers that provide great sound reproduction, and the single earcap \\"zound plug,\\" which allows your friend to plug their headphones into yours so you can both enjoy the same sounds. The cord is also wrapped in fabric to help prevent tangles. Great for anyone who''s looking for an extra stylish pair of day-to-day headphones.', 'padded headband and comfortable ear cushions wrapped in denim fabric', 'can be folded as small as your fist for ultimate portability', 'monochromatic design with no logos', '47\\" fabric wrapped cord prevents tangles', 'headphones', 'headphones/plattan-denim.jpg'),
(29, 'Urbanears', 'Plattan Headphones - Quilted Black', '59.99 ', 'The Quilted Plattan is the first in Urbanears'' \\"editions\\" line of headphones. The editions headphones offer something special, and with the Quilted model, they feature unique all-over quilted stitching on the the padded headband and ear cushions. These headphones inherit the features of other Plattanss including the classic style that can be folded as small as your fist for ultimate portability, the handmade 36mm drivers that provide great sound reproduction, and the single earcap \\"zound plug,\\" which allows your friend to plug their headphones into yours so you can both enjoy the same sounds. The cord is also wrapped in fabric to help prevent tangles. Great for anyone who''s looking for an extra stylish pair of day-to-day headphones.', 'one earcap features a \\"zound plug,\\" which allows your friend to plug their headphones into yours so you can both enjoy the same sounds', 'can be folded as small as your fist for ultimate portability', 'monochromatic design with no logos', '47\\" fabric wrapped cord prevents tangles', 'headphones', 'headphones/plattan-black.jpg'),
(30, 'Urbanears', 'Bagis In-Ear Headphones', '30.00', 'The Bagis is a compact version of the full Urbanears experience. It''s an earplug construction for a direct sound and efficient noise reduction. It features rubber housing along with a combined fabric and TPE cord to eliminate distortions caused by friction. As a bonus each earpiece snaps together, allowing you to carry them around your neck when not in use. So now you know where they''re at.', 'compact in-ear design', 'handmade 9mm drivers', '3 sets of sleeves included to ensure a perfect fit', 'tangle resistant fabric and TPE cord', 'headphones', 'headphones/urbanears-buds.jpg'),
(31, 'Ortofon', 'Pro-S OM Cartridge', '44.99', 'Although the Pro is the most inexpensive of the Ortofon line, it still performs better than most DJ cartridges on the market. Unless you are playing at club with a large sound system, you won''t notice much difference between models in terms of sound quality. The Pro is a very versatile cartridge suitable for all types of at home djing.', 'most affordable Ortofon model, but offers great performance', 'great for all-types of djing', 'strong tracking force', 'wider stylus for less record wear', 'catridge', 'catridges/ortofon-pro-s.jpg'),
(32, 'Ortofon', 'QBert Concorde Cartridge Kit', '173.99', 'Co-developed by one of the most legendary DJs of all time, the Ortofon Q.Bert provides unsurpassed handling, high output voltage, and low wear characteristics that literally put it in a class of its own. Turntablists and mix DJs alike will appreciate the strong output of this cartridge, coupled with unrivaled tracking ability and sonic characteristics. The Q.Bert features a more subdued high end, which helps to minimize surface noise from worn vinyl, and an accentuated mid-range to help bring scratching to the front of the sound stage.', 'co-developed by DJ Q-Bert with an emphasis on active sound', 'recommended for scratching', 'highest output for Ortofon line (11mV)', 'includes extra stylus', 'catridge', 'catridges/ortofon-qbert.jpg'),
(33, 'Ortofon', 'Scratch Concorde Cartridge Kit', '146.99', 'For DJs that require increased tracking ability, the Scratch is up to the task. Featuring a reinforced rubber suspension, DJs need not worry about compromising sound quality and stylus life when working with higher tracking forces. With solid bass reproduction and extended highs, the Scratch is great for any style, providing energetic, in-your-face sound.', 'reinforced rubber suspension of high tracking and durability', 'suitable for all types of djing, especially scratching and back cueing', 'versatile sound for all types of music, solid bass and extended highs', 'includes extra stylus', 'catridge', 'catridges/ortofon-scratch.jpg'),
(34, 'Shure', 'M44-7 Cartridge', '69.95', 'The undisputed king of scratch cartridges, the M447 is one of the most reliable and skip-resistant cartridges on the market. When set up properly and broken in, it will stick to the groove better than anything else we''ve encountered. The proof is in the users, and just about every big name is the scratch dj world swears by the M447. The M44-7 also boasts a very low tracking force, which translates into minimum record wear.', 'scratch / hip-hop DJ standard', 'high skip resistance + low record wear', 'strong bass and loud output', 'includes extra stylus', 'catridge', 'catridges/shure-m44.jpg'),
(35, 'Shure', 'M92E Cartridge', '39.95', 'If you''ve got an old turntable at home that doesn''t have a standard 1200''s style headshell mount, this is the answer. The M92E will fit 85% of all turntables, capable of both P-mount style (one small screw on the side) and the standard headshell mount. It also produces Shure quality sound with relatively low record wear.', 'hi-fi listening cartridge', 'will replace cartridge for most old turntables', 'mounting capability', '1 year warranty', 'catridge', 'catridges/shure-m92.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
